version: '3'
services:
  skyeye:
    image: skyeye:5adbccd
    ports:
      - "8088:8088"
    volumes:
      - ./config/config.dev.yaml:/app/config.dev.yaml
      - ./config/flashloan.txt:/app/flashloan.txt
      - /mnt/dedaub:/app/dedaub
    command: /app/skyeye http
