http_server:
  host: localhost
  port: 8088
  apikey:
  client_max_conns: 5
  dedaub_code_path: /mnt/dedaub/bsc
  multi_evm_clients:
    ethereum:
      provider_url:
    bsc:
      provider_url:

scan_infos:
  ethereum:
    apikeys:
    solidity_code_path: /mnt/solidity/ethereum
    address_nonce_threshold: 200000
  bsc:
    apikeys:
    solidity_code_path: /mnt/solidity/bsc
    address_nonce_threshold: 200000

etl:
  chain: ethereum
  worker: 10
  previous_file: ./config/.previous
  provider_url:
  scan_interval: 0

postgresql:
  host: localhost
  port: 5432
  user: test
  password: test
  database: test
  log_mode: true
  max_idle_conns: 5
  max_open_conns: 10

redis:
  addr: localhost:6379
  database: 1
  max_idle_conns: 5