http_server:
  host: localhost
  port: 8080

postgresql:
  user: postgres
  password: postgres
  database: postgres
  host: localhost
  port: 5432
  log_mode: true
  max_idle_conns: 5
  max_open_conns: 10

etl:
  provider_url:
  chain: ethereum
  worker: 10
  previous_file:
